project:
  type: book

book:
  title: "Billingsley Solutions"
  sidebar:
    contents:
      - index.qmd
      - part: "Chapter 1. Probability"
        chapters:
          - section: "Section 1: Borel's Normal Number Theorem"
            contents:
              - ch01/sec01/S1P1.qmd
              - ch01/sec02/prob02.qmd
          - section: "Section 2: Fields"
            contents:
              - ch01/sec02/prob01.qmd

format:
  html:
    theme: cosmo
    code-copy: true
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>
    # This pulls in your custom LaTeX commands for the web
    include-before-body: notations.tex 
  pdf:
    documentclass: scrreprt
    include-in-header: commands.tex
